answers = ["Papercut",
"One Step Closer",
"With You",
"Points of Authority",
"Crawling",
"Runaway",
"By Myself",
"In the End",
"A Place for My Head",
"Forgotten",
"Cure for the Itch",
"Pushing Me Away",
"My December",
"High Voltage",
"Foreword",
"Don't Stay",
"Somewhere I Belong",
"Lying from You",
"Hit the Floor",
"Easier to Run",
"Faint",
"Figure.09",
"Breaking the Habit",
"From the Inside",
"Nobody's Listening",
"Session",
"Numb",
"Wake",
"Given Up",
"Leave Out All the Rest",
"Bleed It Out",
"Shadow of the Day",
"What I've Done",
"Hands Held High",
"No More Sorrow",
"Valentine's Day",
"In Between",
"In Pieces",
"The Little Things Give You Away",
"No Roads Left",
"Not Alone",
"The Requiem",
"The Radiance",
"Burning in the Skies",
"Empty Spaces",
"When They Come for Me",
"Robot Boy",
"Jornada del Muerto",
"Waiting for the End",
"Blackout",
"Wretches and Kings",
"Wisdom, Justice, and Love",
"Iridescent",
"Fallout",
"The Catalyst",
"The Messenger",
"A Thousand Suns: The Full Experience",
"Blackbirds",
"Lost in the Echo",
"In My Remains",
"Burn It Down",
"Lies Greed Misery",
"I'll Be Gone",
"Castle of Glass",
"Victimized",
"Roads Untraveled",
"Skin to Bone",
"Until It Breaks",
"Tinfoil",
"Powerless",
"Nobody Can Save Me",
"Good Goodbye",
"Talking to Myself",
"Battle Symphony",
"Invisible",
"Heavy",
"Sorry for Now",
"Halfway Right",
"One More Light",
"Sharp Edges" ]