# TODO: replace by YAML
quotations = [
    '"We all make choices in life, but in the end our choices make us." Andrew Ryan, Bioshock',
    '"Get over here!" Scorpion, Mortal Kombat',
    '"What is better? To be born good or to overcome your evil nature through great effort?" Paarthurnax, Elder Scrolls V: Skyrim',
    '"The right man in the wrong place can make all the difference in the world." G-Man, Half-Life 2',
    '"Stand in the ashes of a trillion dead souls, and asks the ghosts if honor matters. The silence is your answer." Javik, Mass Effect 3',
    '"Bring me a bucket, and I\'ll show you a bucket!" Psycho, Borderlands 2',
    '"Wanting something does not give you the right to have it." Ezio Auditore, Assassin’s Creed 2',
    '"Even in dark times, we cannot relinquish the things that make us human." Khan, Metro 2033',
    '"How many are there in you? Whose hopes and dreams do you encompass? Could you but see the eyes in your own, the minds in your mind, you would see how much we share." Vortigaunt, Half-Life 2',
    "\"The healthy human mind doesn't wake up in the morning thinking this is its last day on Earth. But I think that's a luxury, not a curse. To know you're close to the end is a kind of freedom. Good time to take... inventory.\" Captain Price, Call of Duty: Modern Warfare 2",
    '"It’s a funny thing, ambition. It can take one to sublime heights or harrowing depths. And sometimes they are one and the same." Emily Kaldwin, Dishonored',
    '"A hero need not speak. When he is gone, the world will speak for him." Halo',
    '"No gods or kings. Only man." Andrew Ryan, Bioshock',
    '"Some trees flourish, others die. Some cattle grow strong, others are taken by wolves. Some men are born rich enough and dumb enough to enjoy their lives. Ain’t nothing fair." John Marston, Red Dead Redemption',
    '"You can’t break a man the way you break a dog, or a horse. The harder you beat a man, the taller he stands." The Jackal, Far Cry 2',
    "\"It's time to kick ass and chew bubblegum... and I'm all outta gum.\" Duke Nukem, Duke Nukem 3D",
    '"Life is cruel. Of this I have no doubt. One can only hope that one leaves behind a lasting legacy. But so often, the legacies we leave behind...are not the ones we intended." Queen Myrrah, Gears of War 2',
    '"…" Link, The Legend of Zelda (any of them)',
    '"If our lives are already written, it would take a courageous man to change the script." Alan Wake, Alan Wake',
    '"It\'s easy to forget what a sin is in the middle of a battlefield." Solid Snake, Metal Gear Solid',
    '"You know, being Caroline taught me a valuable lesson. I *thought* you were my greatest enemy, when all along you were my best friend. The surge of emotion that shot through me when I saved your life taught me an even more valuable lesson - where Caroline lives in my brain." GLaDOS, Portal 2',
    '"The courage to walk into the Darkness, but strength to return to the Light." Parables of the Allspring, Destiny',
    '"Who are you, that do not know your history?" Ulysses, Fallout New Vegas',
    '"Don\'t wish it were easier, wish you were better." Chief, Animal Crossing',
    '"The world fears the inevitable plummet into the abyss. Watch for that moment and when it comes, do not hesitate to leap. It is only when you fall that you learn whether you can fly." Flemeth, Dragon Age Origins',
    "\"Most test subjects do experience some cognitive deterioration after a few months in suspension. Now you've been under for... quite a lot longer, and it's not out of the question that you might have a very minor case of serious brain damage. But don't be alarmed, alright? Although, if you do feel alarm, try to hold onto that feeling because that is the proper reaction to being told you have brain damage.\" Wheatley, Portal 2",
    '"Trust me." BT-7274, Titanfall 2',
    '"If history only remembers one in a thousands of us, then the future will be filled with stories of who we were and what we did." Battlefield 1',
    '"We\'re made up of thousands of parts with thousands of functions all working in tandem to keep us alive. Yet if only one part of our imperfect machine fails, life fails. It makes one realize how fragile, how flawed we are." Ingun Black-Briar, Elder Scrolls V: Skyrim',
    '"Nothing is true, everything is permitted." Ezio Auditore, Assassin’s Creed 2',
    '"NOTHING IS MORE BADASS THAN TREATING A WOMAN WITH RESPECT!" Mr. Torgue, Borderlands 2',
    '"Good men mean well. We just don\'t always end up doing well." Isaac Clarke, Dead Space 3',
    '"It’s dangerous to go alone, take this!" Old Man, The Legend of Zelda',
    '"War. War never changes." Narrator, Fallout 3',
    '"AAAAAAAAAAAAHHHRHGHHHGH thump" Tarhiel, Elder Scrolls III: Morrowind',
    "\"The best solution to a problem is usually the easiest one. And I'll be honest - killing you is hard. You know what my days used to be like? I just tested. Nobody murdered me, or put me in a potato, or fed me to birds. I had a pretty good life. And then you showed up. You dangerous, mute lunatic. So you know what? You win. Just go. [chuckles] It's been fun. Don't come back.\" GLaDOS, Portal 2",
    "\"Boss... you were right. It's not about changing the world. It's about doing our best to leave the world... the way it is. It's about respecting the will of others, and believing in your own.\" Big Boss, Metal Gear Solid 4",
    '"Often when we guess at others\' motives, we reveal only our own." Mara Sov, Destiny',
    '"Endure and survive." Ellie, The Last of Us',
    '"Death is inevitable. Our fear of it makes us play safe, blocks out emotion. It\'s a losing game. Without passion, you are already dead." Max Payne, Max Payne 2: The Fall of Max Payne',
    '"..." Gordon Freeman, Half-Life',
    '"You gave them the one thing that was stolen from them. A chance. A chance to learn. To find love. To live. And in the end what was your reward? You never said. But I think I know: a family." Brigid Tenenbaum, Bioshock',
    '"Protocol one: link to Pilot. Protocol two: uphold the mission. Protocol three: protect the Pilot." BT-7274, Titanfall 2',
    '"You are here, and it’s beautiful, and escaping isn’t always something bad." Delilah, Firewatch',
    '"You can’t undo what you’ve already done, but you can face up to it." Frank Coleridge, Silent Hill: Downpour',
    '"I miss the internet" Graffiti, Left 4 Dead',
    '"Life is all about resolve. Outcome is secondary." Waka, Okami',
    '"Stay awhile, and listen!" Deckard Cain, Diablo II',
    '"Thank you Mario! But our Princess is in another castle!" Toad, Super Mario Bros.',
    '"It\'s a-me, Mario!" Mario Auditore, Assassin’s Creed II',
    '"I WILL KILL YOUR DICKS!" Trishka Novak, Bulletstorm',
    '"What is a man? A miserable little pile of secrets." Dracula, Castlevania: Symphony of the Night',
    '"My brothers and sisters... I will see you again. Someday. You\'ve given them back to me." Lord Saladin Forge, Destiny',
    '"…" *cocks shotgun* Doomguy, DOOM',
    '"Finish him!" Mortal Kombat announcer, Mortal Kombat',
    '"A man chooses; a slave obeys." Andrew Ryan, BioShock',
    '"We both said a lot of things that you\'re going to regret. But I think we can put our differences behind us. For science. You monster." GLaDOS, Portal 2',
    '"Snake? Snake? SNAAAAAAAAKE!!!" The Colonel, Metal Gear Solid 2',
    '"Wake me when you need me." John-117, Halo 3',
    '"Grass grows, birds fly, sun shines, and brother, I hurt people." The Scout, Team Fortress 2',
    '"Requiescat in pace." Ezio Auditore, Assassin’s Creed II',
    '"Every puzzle has an answer." Professor Layton, Professor Layton and the Curious Village',
    '"Hey! Listen!" Na’vi, The Legend of Zelda: Ocarina of Time',
    '"I used to be an adventurer like you, until I took an arrow to the knee." Town Guard, Elder Scrolls V: Skyrim',
    '"It’s super effective!" Pokemon series',
    '"The Kid just rages for a while." Narrator, Bastion',
    '"Space. Space. I\'m in space. SPAAAAAAACE!" Space Core, Portal 2',
    '"The ending isn’t any more important than any of the moments leading to it." Dr Rosalene, To The Moon',
    '"Do a barrel roll!" Star Fox 64',
    '"I’m rackin\' my brain trying to think of a name for that diamond pony I bought. I was gonna call it “piss-for-brains” in honor of you, but that just feels immature. Maybe...”Butt Stallion”?" Handsome Jack, Borderlands 2',
    '"No matter how dark the night, morning always comes, and our journey begins anew." Lulu, Final Fantasy X',
    '"Hope is what makes us strong. It is why we are here. It is what we fight with when all else is lost." Pandora, God of War 3',
    '"A sword wields no strength unless the hands that holds it has courage." The Hero’s Shade, Legend of Zelda: Twilight Princess',
    '"Steel wins battles. Gold wins wars." Davion the Dragon Knight, DOTA 2',
    '"War. War never changes. But men do, through the roads they walk." The narrator, Fallout: New Vegas',
    '"Science isn’t about why! It’s about why not!" Cave Johnson, Portal 2',
    '"Stop right there, criminal scum!" Town Guard, Elder Scrolls IV: Oblivion',
    '"There was a HOLE here. It\'s gone now." In-game text, Silent Hill 2',
    '"I don’t want to set the world on fire…" Song, Fallout 3',
    '"Hard to see big picture behind pile of corpses." Mordin Solus, Mass Effect 3',
    '"Tell me Bats. What are you really scared of? Failing to save this cesspool of a city? Not finding the Commissioner in time? Me, in a thong?" The Joker, Batman: Arkham Asylum',
    '"Does this unit have a soul?" Legion, Mass Effect 3',
    '"You are not a good person. You know that, right? Good people don\'t end up here." GLaDOS, Portal 2',
    '"Federico: It is a good life we lead, brother. Ezio: The best. May it never change. Federico: And may it never change us." Federico and Ezio Auditore, Assassin’s Creed 2',
    "\"I raised you, and loved you, I've given you weapons, taught you techniques, endowed you with knowledge. There's nothing more for me to give you. All that's left for you to take is my life.\" The Boss, Metal Gear Solid 3",
    "\"It's more important to master the cards you're holding than to complain about the ones your opponents were dealt.\" Grimsley, Pokémon Black and White",
    '"The price of freedom is eternal vigilance." Admiral Tolwyn, Wing Commander IV',
    '"Are you a boy or a girl?" Pokemon',
    "\"LOTTA PEOPLE BEEN ASKIN' WHY MY VOICE BEEPS ALL THE TIME. THE TORGUE SHAREHOLDERS WIRED MY VOICEBOX WITHA DIGITAL CENSOR SO I CAN'T SAY STUFF LIKE SH*T, C*CK, OR P*SSY F*CKIN' D*CKBALLS! THATS HALF MY F*CKIN' VOCABULARY, IT'S GODDAMN BULLSH*T!\" Mr Torgue, Borderlands 2",
    '"War is where the young and stupid are tricked by the old and bitter into killing each other." Niko Bellic, GTA IV',
    '"What is a man but the sum of his memories? We are the stories we live! The tales we tell ourselves!" Clay Kaczmarek, Assassin’s Creed Brotherhood',
    "\"When life gives you lemons, don't make lemonade. Make life take the lemons back! Get mad! I don't want your damn lemons! What am I supposed to do with these?! Demand to see life's manager! Make life rue the day it thought it could give Cave Johnson lemons! Do you know who I am?! I'm the man who's gonna burn your house down! With the lemons! I'm gonna get my engineers to invent a combustible lemon that burns your house down!\" Cave Johnson, Portal 2",
    '"Praise the sun!" Solaire of Astora, Dark Souls',
    '"Send me out...with a bang." Sgt. Avery Johnson, Halo 3',
    '"You have died of dysentery." Oregon Trail',
    '"Batman: You want to know something funny? Even after everything you\'ve done, I would have saved you. The Joker: [laughs, coughs] Actually that is pretty funny." Batman: Arkham Asylum',
    '"Do you like hurting other people?" Richard, Hotline Miami',
    '"YOU DIED" Dark Souls',
    '"Ghost: This path should lead us straight to the grave. [pause] Ghost: The World\'s Grave. Not ours." Ghost, Destiny',
    "\"I've struggled a long time with survivin', but no matter what you have to find something to fight for.\" Joel, The Last of Us",
    '"Batman must save Gotham." Alfred, Batman: Arkham City',
]
