name: Development
on:
  push:
    branches-ignore:
      - stage
      - master
jobs:
  deploy:
      name: Check code
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            cache: 'pip'
        - name: Install linters
          run: |
            pip install --upgrade pip
            pip install pylint
        - name: Check pylint
          run:
            pylint src
