name: Development
on:
  push:
    branches-ignore:
      - stage
      - master
jobs:
  deploy:
      name: Check code
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: ricardochaves/python-lint@v1.4.0
          with:
            python-root-list: "src"
            use-pylint: true
            use-pycodestyle: false
            use-flake8: false
            use-black: true
            use-mypy: false
            use-isort: true
            extra-pylint-options: "--rcfile ./.pylintrc"
